version: "3.7"
services:
 web:
  image: fabiobentoluiz/libfprint_web:latest
  depends_on:
   - database
  restart: "no"
  ports:
   - "80:8080"
  environment:
   - SPRING_PROFILES_ACTIVE=docker
 database:
  image: hypriot/rpi-mysql:arm-5.5
  restart: unless-stopped
  environment: 
   - MYSQL_ROOT_PASSWORD=123456
  command: --init-file /tmp/libfprint.sql
  volumes:
    - /tmp/docker/volumes/mysql:/var/lib/mysql
    - ../database/libfprint.sql:/tmp/libfprint.sql
  ports:
   - "5000:3306"
 enroll:
  image: fabiobentoluiz/libfprint_enroll:latest
  depends_on:
   - web
  restart: unless-stopped
  environment:
   - WEBSERVER=web
   - WEBSERVER_PORT=8080
  volumes:
   - /dev:/dev
  privileged: true
  ports:
   - "5001:3000"
