version: "3.7"
services:
 enroll:
  image: fabiobentoluiz/libfprint_enroll:latest
  ports:
   - "5000:3000"
  #restart: unless-stopped
  environment:
   - WEBSERVER=192.168.2.120
   - WEBSERVER_PORT=8080
